module.exports = [
//   "https://ticketleader.evenue.net/cgi-bin/ncommerce3/SEGetEventInfo?ticketCode=GS%3aTKTLDR%3aMJ23%3a0318MJA%3a&linkID=tktldr",
//   "https://ev3.evenue.net/cgi-bin/ncommerce3/SEGetEventInfo?ticketCode=GS%3aNHRA%3a23GF%3aGF1SU%3a&linkID=nhra",
//   "https://ticketleader.evenue.net/cgi-bin/ncommerce3/SEGetEventInfo?ticketCode=GS%3aTKTLDR%3aMJ23%3a0319MJA%3a&linkID=tktldr",
//   "https://kingcenter.evenue.net/cgi-bin/ncommerce3/SEGetEventInfo?ticketCode=GS%3aARTS%3aKC19%3a012223%3a&linkID=king-arts",
//   "https://fightingillini.evenue.net/cgi-bin/ncommerce3/SEGetEventInfo?ticketCode=GS%3aILLINOIS%3aF22%3a05%3a&linkID=illinois",
//   "https://portland5.evenue.net/cgi-bin/ncommerce3/SEGetEventInfo?ticketCode=GS%3aPCPA%3aPCPA22%3aKA0311%3a&linkID=pcpa",
//   "https://ev3.evenue.net/cgi-bin/ncommerce3/SEGetEventInfo?ticketCode=GS%3aNHRA%3a23PA%3aPA1SA%3a&linkID=nhra",
//   "https://calbears.evenue.net/cgi-bin/ncommerce3/SEGetEventInfo?ticketCode=GS%3aCTO%3aWB22%3aWB10%3a&linkID=cal",
//   "https://ev3.evenue.net/cgi-bin/ncommerce3/SEGetEventInfo?ticketCode=GS%3aNHRA%3a23GF%3aGF1SA%3a&linkID=nhra",
//   "https://pplcenter.evenue.net/cgi-bin/ncommerce3/SEGetEventInfo?ticketCode=GS%3aALLENTOWN%3aFELD22%3aDOI0121M%3a&linkID=global-allentown",
//   "https://texastech.evenue.net/cgi-bin/ncommerce3/SEGetEventInfo?ticketCode=GS%3aTTU%3aW22%3aW15%3a&linkID=ttu",
//   "https://usajaguars.evenue.net/cgi-bin/ncommerce3/SEGetEventInfo?ticketCode=GS%3aATHLETICS%3aWB23%3aWB10%3a&linkID=usal-athletics",
//   "https://texasperformingarts.evenue.net/cgi-bin/ncommerce3/SEGetEventInfo?ticketCode=GS%3aPAC%3aUTP23%3aBH04233%3a&linkID=tex-pac",
//   "https://ev3.evenue.net/cgi-bin/ncommerce3/SEGetEventInfo?ticketCode=GS%3aNHRA%3a23PA%3aPA1SA%3a&linkID=nhra",
//   "https://portland5.evenue.net/cgi-bin/ncommerce3/SEGetEventInfo?ticketCode=GS%3aPCPA%3aBW22%3aB230105B%3a&linkID=pcpa",
//   "https://portland5.evenue.net/cgi-bin/ncommerce3/SEGetEventInfo?ticketCode=GS%3aPCPA%3aPCPA22%3aAS0401%3a&linkID=pcpa",
//   "https://portland5.evenue.net/cgi-bin/ncommerce3/SEGetEventInfo?ticketCode=GS%3aPCPA%3aPCPA22%3aAS0120%3a&linkID=pcpa",
//   "https://ticketleader.evenue.net/cgi-bin/ncommerce3/SEGetEventInfo?ticketCode=GS%3aTKTLDR%3aMJ23%3a0318MJA%3a&linkID=tktldr",
"https://bgsufalcons.evenue.net/cgi-bin/ncommerce3/SEGetEventInfo?ticketCode=GS%3aATHLETICS%3aW22%3aW07%3a&linkID=bgsu-athletics",
"https://hyveetix.evenue.net/cgi-bin/ncommerce3/SEGetEventInfo?ticketCode=GS%3aGLOBAL-IOWA%3aH23%3aW20%3a&linkID=global-iowa",
"https://goredbirds.evenue.net/cgi-bin/ncommerce3/SEGetEventInfo?ticketCode=GS%3aISU%3aB22%3aB07%3a&linkID=illinoisst",
"https://ugapac.evenue.net/cgi-bin/ncommerce3/SEGetEventInfo?ticketCode=GS%3aUGAARTS%3aUA2223%3a126%3a&linkID=ta-ugaarts",
"https://uh.evenue.net/cgi-bin/ncommerce3/SEGetEventInfo?ticketCode=GS%3aHOUSTON%3aMB22%3aMB12%3a&linkID=houston",
];
